baseURL = "https://publicmx.com"
languageCode = "en-us"
title = "Mostly Rambling"
theme = "PaperMod"
enableInlineShortcodes = true
disableKinds = ["taxonomy", "term"]

[params]
  description = "Just a bunch of rambling about almost anything."

[minify]
  minifyOutput = true

[menu]

  [[menu.main]]
    name = "Archive"
    url = "archives"
    weight = 2
  [[menu.main]]
    name = "Search"
    url = "search"
    weight = 2

[permalinks]
  posts = "/posts/:contentbasename/"
  
[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true

[outputs]
  home = ['html', 'rss', 'json']
